--DATA PREPARATION & UNDERSTANDING

--1. What is the total number of rows in each of the 3 tables in the database?
SELECT COUNT(*) CustomerCount FROM Customer
SELECT COUNT(*) prod_cat_info_count FROM prod_cat_info
SELECT COUNT(*) TransactionsCount FROM Transactions

--2. What is the total number of transactions that have return?

SELECT COUNT(DISTINCT(transaction_id)) return_transaction_count 
FROM Transactions
WHERE Qty < 0;

--3. Convert the date variables into valid date formats.
ALTER TABLE Transactions
ALTER COLUMN tran_date DATETIME2

--4. What is the time range of the transaction data available for analysis? 
--Show the output in number of days, months and years simultaneously in different columns.

SELECT 
DATEDIFF(YEAR,MIN(tran_date),MAX(tran_date)) AS data_time_range_years,
DATEDIFF(MONTH,MIN(tran_date),MAX(tran_date)) AS data_time_range_months,
DATEDIFF(DAY,MIN(tran_date),MAX(tran_date)) AS data_time_range_days
FROM Transactions

--5)Which product category does the sub-category "DIY" belong to?
SELECT prod_cat, prod_subcat
FROM prod_cat_info
WHERE prod_subcat = 'DIY'


--DATA ANALYSIS

--1. Which channel is most frequently used for transactions?
SELECT TOP 1 STORE_TYPE, COUNT(STORE_TYPE)
FROM Transactions
GROUP BY Store_type
ORDER BY COUNT(STORE_TYPE) DESC;

--2. What is the count of Male and Female customers in the database?
SELECT GENDER, COUNT(GENDER) AS [COUNT OF GENDER]
FROM Customer
GROUP BY Gender;

--3. From which city do we have the maximum number of customers and how many?
SELECT TOP 1 CITY_CODE, COUNT(CITY_CODE)
FROM Customer
GROUP BY city_code
ORDER BY COUNT(CITY_CODE) DESC;

--4. How many sub-categories are there under the Books category?
SELECT COUNT(PROD_SUBCAT) AS [BOOKS_SUBCAT_COUNT]
FROM prod_cat_info
WHERE prod_cat='Books';

--5. What is the maximum quantity of products ever ordered?
SELECT MAX(QTY)	AS MaxQuantity
FROM Transactions;

--6. What is the net total revenue generated in categories Electronics and Books? (assuming net total revenue would be 
--calculated after deducting tax from the total_amt)
SELECT PROD_CAT_CODE, SUM(TOTAL_AMT-TAX) AS NetRevenue
FROM TRANSACTIONS
WHERE PROD_CAT_CODE IN (3,5)
GROUP BY prod_cat_code;

--7. How many customers have > 10 transactions with us, excluding returns?
SELECT cust_id,COUNT(TRANSACTION_ID) AS TransactionCount
FROM Transactions
WHERE Qty>0
GROUP BY cust_id
HAVING COUNT(TRANSACTION_ID)>10;


--8. What is the combined revenue earned from the "Electronics" & "Clothing" categories, from "Flagship Stores"?
SELECT SUM(TOTAL_AMT) RevElecClothing
FROM Transactions
WHERE Store_type = 'Flagship store' AND prod_cat_code IN (1,3);


--9. What is the total revenue generated from "Male" customers in "Electronics" category? Output should display total
--revenue by prod sub-cat.

SELECT T.prod_subcat_code,SUM(TOTAL_AMT) TOTALREV 
FROM Transactions T
LEFT JOIN Customer C
ON T.cust_id=C.customer_Id
WHERE GENDER = 'M' AND T.prod_cat_code = 3
GROUP BY T.prod_subcat_code;


--10. What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of
--sales?
WITH SalesReturns As(
	SELECT  
		P.prod_sub_cat_code AS ProductSubcategory,
		SUM(CASE WHEN Qty>0 THEN T.total_amt ELSE 0 END) TotalSales,
		SUM(CASE WHEN Qty<0 THEN T.total_amt ELSE 0 END) TotalReturns
	FROM 
		Transactions T
	JOIN 
		prod_cat_info P ON T.prod_subcat_code = P.prod_sub_cat_code
	GROUP BY
		P.prod_sub_cat_code)

SELECT TOP 5 ProductSubcategory, TotalSales, TotalReturns, (TotalSales/(TotalSales+TotalReturns))*100 AS SalesPercentage
FROM 
	SalesReturns
ORDER BY
	TotalSales DESC;


--11. For all customers aged between 25 to 35 years, find what is the total revenue generated by these columns in last 30
--days of transactions from max transaction date available in the data?
WITH CustomerAgeRange AS (
	SELECT 
		customer_id,
		DOB,
		Gender
	FROM 
		Customer
	WHERE
		DOB BETWEEN DATEADD(YEAR, -35,  (SELECT MAX(tran_date) FROM Transactions)) AND DATEADD(YEAR, -25,  (SELECT MAX(tran_date) FROM Transactions))
)

SELECT 
	C.customer_Id,
	C.DOB,
	C.Gender,
	SUM(T.TOTAL_AMT) AS TOTALREVENUE
FROM 
	CustomerAgeRange C
JOIN
	Transactions T ON C.customer_Id = T.cust_id
WHERE
	T.tran_date BETWEEN DATEADD(DAY, -30, (SELECT MAX(TRAN_DATE) FROM Transactions)) AND (SELECT MAX(TRAN_DATE) FROM Transactions)
GROUP BY C.customer_Id, C.DOB, C.Gender
	

--12. Which product category has seen the max value of returns in the last 3 months of transactions?
SELECT Top 1 prod_cat_Code, SUM(total_amt) cat_sales
FROM Transactions
WHERE Qty < 0 AND tran_date >= DATEADD(MONTH, -3, (SELECT MAX(tran_date) FROM Transactions))
GROUP BY prod_cat_code
ORDER BY SUM(total_amt) DESC

--13.  Which store-type sells the maximum products; by value of sales amount and by quantity sold?
SELECT TOP 1 Store_type, SUM(Qty) Qty_sold, SUM(total_amt) Sale_amt
FROM Transactions
GROUP BY Store_type
ORDER BY SUM(total_amt) DESC, SUM(Qty) DESC;


--14. What are the categories for which the average revenue is above the overall average.
SELECT prod_cat_code, AVG(total_amt) avg_sales
FROM Transactions
GROUP BY prod_cat_code
HAVING AVG(total_amt)> (SELECT AVG(total_amt) FROM Transactions)


--15. Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.
WITH Top5Categories AS (
	SELECT TOP 5 prod_cat_code, SUM(Qty) as total_quantity
	FROM Transactions
	GROUP BY prod_cat_code
	ORDER BY SUM(Qty) DESC
)

SELECT T.prod_cat_code, T.prod_subcat_code, AVG(total_amt) avg_sales, SUM(total_amt) tot_sales
FROM Transactions T 
JOIN Top5Categories T5 
ON T.prod_cat_code = T5.prod_cat_code
GROUP BY T.prod_cat_code,T.prod_subcat_code